#!/bin/bash
PATH=./node_modules/.bin:$PATH

###############################################################################
# ACTIONS

function build {
  echo "This is the build action"
}

function test {
  truffle test
}

###############################################################################
# DEFAULT => INFO

function default {
  echo "$0 <task> <args>"
  echo
  echo "Available tasks:"
  compgen -A function | cat -n
}


TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
